### ISSUE TITLE
RemoteActionTest sometimes waits endlessly on exeuction state

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco#51]
Sometimes the remote action test fails on [waiting for the execution state](https://github.com/openbase/bco/blob/1de31afb6e644e1f0f996634981509f705a64f4f/module/dal/test/src/test/java/org/openbase/bco/dal/test/action/RemoteActionTest.java#L145). This only happens seldom. Using a debugger, we could see that the state of the action in the data type of the unit remote is `EXECUTING`. Therefore the following things have to be investigated:
* Is the event filtered because of a permission issue?
* Can it happen that the notification of the state change is skipped? 👎 
* Does the RemoteAction handle the notifications correctly?

**Comment by DivineThreepwood** [comment]
@pLeminoq We performed the debugging on remote side and could see that the action was already marked as executing in the target remote action list, right? Thus, this seems to be a remote issue and we can skip `Can it happen that the notification of the state change is skipped?`.

**Comment by pLeminoq** [comment]
Yes, you are right. With the notification skip, I meant the observer notification of the remote.

**Comment by DivineThreepwood** [comment]
Even when the debugging seems to target the remote site, I would guess that this bug is addressed by the next bco PR that fixes a bug where the action list was not always correctly synchronized with the data builder.

**Comment by DivineThreepwood** [comment]
please reopen otherwise.
